name: Deploy Pipeline

#On pull from main branch and request is closed
on:
  pull_request:
    branches:
      - main
    types:
      - closed

#If merged = true run on server, checkout main branch
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

        #Log into docker hub with username and password 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

        #Build and push the docker file with latest
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./BucStop/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bucstop:latest

        #Run deployment script(see deployment document)
      - name: Run Deploy script on the server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd scripts
            ./redeployBucstop.sh
